import type { Footballer } from './useFootballers'
import { getPuzzleNumber } from './useFootballers'

// Full first+last name roster (no letter-count restriction), used by Scout
// Report and Spot the Baller — both pick a player via autocomplete/multiple
// choice rather than typing into a fixed-length grid like Daily, so they
// aren't limited to 6-letter surnames. Generated via scripts/fetch-players.mjs
// (full-roster mode) against the same football-data.org squads as Daily.
export const allFootballers: Footballer[] = [
	{ name: 'aaron bott', club: 'Nottingham Forest', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'aaron hickey', club: 'Brentford', nationality: 'Scotland', position: 'Defender' },
	{ name: 'aaron ramsdale', club: 'Newcastle', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'aaron wan-bissaka', club: 'West Ham', nationality: 'Congo DR', position: 'Defender' },
	{ name: 'abdoullah ba', club: 'Sunderland', nationality: 'France', position: 'Midfielder' },
	{ name: 'abdukodir khusanov', club: 'Manchester City', nationality: 'Uzbekistan', position: 'Defender' },
	{ name: 'adam armstrong', club: 'Wolverhampton', nationality: 'England', position: 'Forward' },
	{ name: 'adam aznou', club: 'Everton', nationality: 'Morocco', position: 'Defender' },
	{ name: 'adam harrison', club: 'Newcastle', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'adam smith', club: 'Bournemouth', nationality: 'England', position: 'Defender' },
	{ name: 'adam webster', club: 'Brighton & Hove Albion', nationality: 'England', position: 'Centre-Back' },
	{ name: 'adam wharton', club: 'Crystal Palace', nationality: 'England', position: 'Midfielder' },
	{ name: 'adama traoré', club: 'West Ham', nationality: 'Spain', position: 'Forward' },
	{ name: 'adrien truffert', club: 'Bournemouth', nationality: 'France', position: 'Defender' },
	{ name: 'ahmed abdullahi', club: 'Sunderland', nationality: 'Nigeria', position: 'Forward' },
	{ name: 'aidan harris', club: 'Newcastle', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'airidas golambeckis', club: 'West Ham', nationality: 'Lithuania', position: 'Defender' },
	{ name: 'alejandro garnacho', club: 'Chelsea', nationality: 'Argentina', position: 'Forward' },
	{ name: 'aleksei fedorushchenko', club: 'Arsenal', nationality: 'Russia', position: 'Goalkeeper' },
	{ name: 'alex cairns', club: 'Leeds United', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'alex iwobi', club: 'Fulham', nationality: 'Nigeria', position: 'Forward' },
	{ name: 'álex jiménez', club: 'Bournemouth', nationality: 'Spain', position: 'Defender' },
	{ name: 'alex murphy', club: 'Newcastle', nationality: 'Ireland', position: 'Defender' },
	{ name: 'alex scott', club: 'Bournemouth', nationality: 'England', position: 'Midfielder' },
	{ name: 'alex toth', club: 'Bournemouth', nationality: 'Hungary', position: 'Midfielder' },
	{ name: 'alexander isak', club: 'Liverpool', nationality: 'Sweden', position: 'Forward' },
	{ name: 'alexis mac allister', club: 'Liverpool', nationality: 'Argentina', position: 'Midfielder' },
	{ name: 'alfie brooks', club: 'Wolverhampton', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'alfie cresswell', club: 'Leeds United', nationality: 'England', position: 'Defender' },
	{ name: 'alfie mcnally', club: 'Fulham', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'alisson becker', club: 'Liverpool', nationality: 'Brazil', position: 'Goalkeeper' },
	{ name: 'alphonse aréola', club: 'West Ham', nationality: 'France', position: 'Goalkeeper' },
	{ name: 'altay bayındır', club: 'Manchester United', nationality: 'Turkey', position: 'Goalkeeper' },
	{ name: 'alysson', club: 'Aston Villa', nationality: 'Brazil', position: 'Forward' },
	{ name: 'amad diallo', club: 'Manchester United', nationality: 'Ivory Coast', position: 'Forward' },
	{ name: 'amadou onana', club: 'Aston Villa', nationality: 'Belgium', position: 'Midfielder' },
	{ name: 'amara nallo', club: 'Liverpool', nationality: 'England', position: 'Defender' },
	{ name: 'amine adli', club: 'Bournemouth', nationality: 'Morocco', position: 'Forward' },
	{ name: 'andré', club: 'Wolverhampton', nationality: 'Brazil', position: 'Midfielder' },
	{ name: 'andre harriman-annous', club: 'Arsenal', nationality: 'England', position: 'Forward' },
	{ name: 'andrés garcia', club: 'Aston Villa', nationality: 'Spain', position: 'Defender' },
	{ name: 'andrew robertson', club: 'Liverpool', nationality: 'Scotland', position: 'Defender' },
	{ name: 'andrey santos', club: 'Chelsea', nationality: 'Brazil', position: 'Midfielder' },
	{ name: 'angel gomes', club: 'Wolverhampton', nationality: 'England', position: 'Midfielder' },
	{ name: 'angus gunn', club: 'Nottingham Forest', nationality: 'Scotland', position: 'Goalkeeper' },
	{ name: 'anthony elanga', club: 'Newcastle', nationality: 'Sweden', position: 'Forward' },
	{ name: 'anthony gordon', club: 'Newcastle', nationality: 'England', position: 'Forward' },
	{ name: 'antoine semenyo', club: 'Manchester City', nationality: 'Ghana', position: 'Forward' },
	{ name: 'anton stach', club: 'Leeds United', nationality: 'Germany', position: 'Midfielder' },
	{ name: 'antonee robinson', club: 'Fulham', nationality: 'USA', position: 'Defender' },
	{ name: 'antoni milambo', club: 'Brentford', nationality: 'Netherlands', position: 'Midfielder' },
	{ name: 'antonín kinský', club: 'Tottenham', nationality: 'Czech Republic', position: 'Goalkeeper' },
	{ name: 'ao tanaka', club: 'Leeds United', nationality: 'Japan', position: 'Midfielder' },
	{ name: 'archie gray', club: 'Tottenham', nationality: 'England', position: 'Defender' },
	{ name: 'archie whitehall', club: 'Nottingham Forest', nationality: 'England', position: 'Midfielder' },
	{ name: 'armando broja', club: 'Burnley', nationality: 'Albania', position: 'Forward' },
	{ name: 'armin pecsi', club: 'Liverpool', nationality: 'Hungary', position: 'Goalkeeper' },
	{ name: 'ashley barnes', club: 'Burnley', nationality: 'England', position: 'Forward' },
	{ name: 'axel disasi', club: 'West Ham', nationality: 'France', position: 'Defender' },
	{ name: 'axel tuanzebe', club: 'Burnley', nationality: 'Congo DR', position: 'Defender' },
	{ name: 'ayden heaven', club: 'Manchester United', nationality: 'England', position: 'Defender' },
	{ name: 'bafodé diakité', club: 'Bournemouth', nationality: 'France', position: 'Defender' },
	{ name: 'bart verbruggen', club: 'Brighton & Hove Albion', nationality: 'Netherlands', position: 'Goalkeeper' },
	{ name: 'bashir humphreys', club: 'Burnley', nationality: 'England', position: 'Defender' },
	{ name: 'ben davies', club: 'Tottenham', nationality: 'Wales', position: 'Defender' },
	{ name: 'ben doak', club: 'Bournemouth', nationality: 'Scotland', position: 'Forward' },
	{ name: 'ben white', club: 'Arsenal', nationality: 'England', position: 'Defender' },
	{ name: 'bendito mantato', club: 'Manchester United', nationality: 'England', position: 'Defender' },
	{ name: 'benjamin casey', club: 'Crystal Palace', nationality: 'England', position: 'Forward' },
	{ name: 'benjamin lecomte', club: 'Fulham', nationality: 'France', position: 'Goalkeeper' },
	{ name: 'benjamin šeško', club: 'Manchester United', nationality: 'Slovenia', position: 'Forward' },
	{ name: 'benoît badiashile', club: 'Chelsea', nationality: 'France', position: 'Defender' },
	{ name: 'bernardo silva', club: 'Manchester City', nationality: 'Portugal', position: 'Midfielder' },
	{ name: 'bernd leno', club: 'Fulham', nationality: 'Germany', position: 'Goalkeeper' },
	{ name: 'bertrand traoré', club: 'Sunderland', nationality: 'Burkina Faso', position: 'Right Winger' },
	{ name: 'beto', club: 'Everton', nationality: 'Guinea-Bissau', position: 'Forward' },
	{ name: 'borna sosa', club: 'Crystal Palace', nationality: 'Croatia', position: 'Defender' },
	{ name: 'boubacar kamara', club: 'Aston Villa', nationality: 'France', position: 'Midfielder' },
	{ name: 'bradley burrowes', club: 'Aston Villa', nationality: 'England', position: 'Forward' },
	{ name: 'brando bailey-joseph', club: 'Arsenal', nationality: 'England', position: 'Forward' },
	{ name: 'brandon austin', club: 'Tottenham', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'brandon pouani', club: 'Burnley', nationality: 'England', position: 'Forward' },
	{ name: 'brenden aaronson', club: 'Leeds United', nationality: 'USA', position: 'Midfielder' },
	{ name: 'brennan johnson', club: 'Crystal Palace', nationality: 'Wales', position: 'Forward' },
	{ name: 'briaden graham', club: 'Everton', nationality: 'Northern Ireland', position: 'Forward' },
	{ name: 'brian brobbey', club: 'Sunderland', nationality: 'Netherlands', position: 'Forward' },
	{ name: 'bruno fernandes', club: 'Manchester United', nationality: 'Portugal', position: 'Midfielder' },
	{ name: 'bruno guimarães', club: 'Newcastle', nationality: 'Brazil', position: 'Midfielder' },
	{ name: 'bryan mbeumo', club: 'Manchester United', nationality: 'Cameroon', position: 'Forward' },
	{ name: 'bukayo saka', club: 'Arsenal', nationality: 'England', position: 'Forward' },
	{ name: 'caleb kporha', club: 'Crystal Palace', nationality: 'England', position: 'Defender' },
	{ name: 'caleb wiley', club: 'Chelsea', nationality: 'USA', position: 'Defender' },
	{ name: 'callum bates', club: 'Everton', nationality: 'England', position: 'Midfielder' },
	{ name: 'callum hudson-odoi', club: 'Nottingham Forest', nationality: 'England', position: 'Forward' },
	{ name: 'callum olusesi', club: 'Tottenham', nationality: 'England', position: 'Midfielder' },
	{ name: 'callum wilson', club: 'West Ham', nationality: 'England', position: 'Forward' },
	{ name: 'calvin bassey', club: 'Fulham', nationality: 'Nigeria', position: 'Defender' },
	{ name: 'calvin ramsay', club: 'Liverpool', nationality: 'Scotland', position: 'Defender' },
	{ name: 'caoimhin kelleher', club: 'Brentford', nationality: 'Ireland', position: 'Goalkeeper' },
	{ name: 'carlos alcaraz', club: 'Everton', nationality: 'Argentina', position: 'Midfielder' },
	{ name: 'carlos baleba', club: 'Brighton & Hove Albion', nationality: 'Cameroon', position: 'Midfielder' },
	{ name: 'carter pinnington', club: 'Liverpool', nationality: 'England', position: 'Defender' },
	{ name: 'casemiro', club: 'Manchester United', nationality: 'Brazil', position: 'Midfielder' },
	{ name: 'ceadach o’neill', club: 'Arsenal', nationality: 'Northern Ireland', position: 'Forward' },
	{ name: 'chadi riad', club: 'Crystal Palace', nationality: 'Morocco', position: 'Defender' },
	{ name: 'charalampos kostoulas', club: 'Brighton & Hove Albion', nationality: 'Greece', position: 'Forward' },
	{ name: 'charlie crewe', club: 'Leeds United', nationality: 'Wales', position: 'Midfielder' },
	{ name: 'charlie gray', club: 'Manchester City', nationality: 'England', position: 'Midfielder' },
	{ name: 'charlie holland', club: 'Chelsea', nationality: 'England', position: 'Midfielder' },
	{ name: 'charlie stevens', club: 'Bournemouth', nationality: 'Wales', position: 'Midfielder' },
	{ name: 'charlie tasker', club: 'Brighton & Hove Albion', nationality: 'England', position: 'Defender' },
	{ name: 'cheick doucouré', club: 'Crystal Palace', nationality: 'Mali', position: 'Midfielder' },
	{ name: 'chemsdine talbi', club: 'Sunderland', nationality: 'Morocco', position: 'Forward' },
	{ name: 'chido obi-martin', club: 'Manchester United', nationality: 'Denmark', position: 'Forward' },
	{ name: 'chimuanya ugochukwu', club: 'Burnley', nationality: 'France', position: 'Midfielder' },
	{ name: 'chris richards', club: 'Crystal Palace', nationality: 'USA', position: 'Defender' },
	{ name: 'chris rigg', club: 'Sunderland', nationality: 'England', position: 'Midfielder' },
	{ name: 'chris wood', club: 'Nottingham Forest', nationality: 'New Zealand', position: 'Forward' },
	{ name: 'chrisantus', club: 'Crystal Palace', nationality: 'Nigeria', position: 'Forward' },
	{ name: 'christian nørgaard', club: 'Arsenal', nationality: 'Denmark', position: 'Midfielder' },
	{ name: 'christian romero', club: 'Tottenham', nationality: 'Argentina', position: 'Defender' },
	{ name: 'christos mandas', club: 'Bournemouth', nationality: 'Greece', position: 'Goalkeeper' },
	{ name: 'cody gakpo', club: 'Liverpool', nationality: 'Netherlands', position: 'Forward' },
	{ name: 'cole palmer', club: 'Chelsea', nationality: 'England', position: 'Midfielder' },
	{ name: 'connor roberts', club: 'Burnley', nationality: 'Wales', position: 'Defender' },
	{ name: 'conor bradley', club: 'Liverpool', nationality: 'Northern Ireland', position: 'Defender' },
	{ name: 'conor gallagher', club: 'Tottenham', nationality: 'England', position: 'Midfielder' },
	{ name: 'conor mcmanus', club: 'Brentford', nationality: 'Ireland', position: 'Midfielder' },
	{ name: 'cristhian mosquera', club: 'Arsenal', nationality: 'Spain', position: 'Defender' },
	{ name: 'crysencio summerville', club: 'West Ham', nationality: 'Netherlands', position: 'Forward' },
	{ name: 'cucurella', club: 'Chelsea', nationality: 'Spain', position: 'Defender' },
	{ name: 'curtis jones', club: 'Liverpool', nationality: 'England', position: 'Midfielder' },
	{ name: 'daichi kamada', club: 'Crystal Palace', nationality: 'Japan', position: 'Midfielder' },
	{ name: 'dan burn', club: 'Newcastle', nationality: 'England', position: 'Defender' },
	{ name: 'dan ndoye', club: 'Nottingham Forest', nationality: 'Switzerland', position: 'Forward' },
	{ name: 'dango ouattara', club: 'Brentford', nationality: 'Burkina Faso', position: 'Forward' },
	{ name: 'daniel ballard', club: 'Sunderland', nationality: 'Northern Ireland', position: 'Defender' },
	{ name: 'daniel bentley', club: 'Wolverhampton', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'daniel james', club: 'Leeds United', nationality: 'Wales', position: 'Forward' },
	{ name: 'daniel muñoz', club: 'Crystal Palace', nationality: 'Colombia', position: 'Defender' },
	{ name: 'danny welbeck', club: 'Brighton & Hove Albion', nationality: 'England', position: 'Forward' },
	{ name: 'dario essugo', club: 'Chelsea', nationality: 'Portugal', position: 'Midfielder' },
	{ name: 'david brooks', club: 'Bournemouth', nationality: 'Wales', position: 'Forward' },
	{ name: 'david raya', club: 'Arsenal', nationality: 'Spain', position: 'Goalkeeper' },
	{ name: 'david wolfe', club: 'Wolverhampton', nationality: 'Norway', position: 'Defender' },
	{ name: 'dean benamar', club: 'Crystal Palace', nationality: 'England', position: 'Midfielder' },
	{ name: 'dean henderson', club: 'Crystal Palace', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'declan rice', club: 'Arsenal', nationality: 'England', position: 'Midfielder' },
	{ name: 'dejan kulusevski', club: 'Tottenham', nationality: 'Sweden', position: 'Midfielder' },
	{ name: 'dennis cirkin', club: 'Sunderland', nationality: 'Latvia', position: 'Defender' },
	{ name: 'destiny udogie', club: 'Tottenham', nationality: 'Italy', position: 'Defender' },
	{ name: 'diego gómez', club: 'Brighton & Hove Albion', nationality: 'Paraguay', position: 'Midfielder' },
	{ name: 'diego león', club: 'Manchester United', nationality: 'Paraguay', position: 'Defender' },
	{ name: 'dilane bakwa', club: 'Nottingham Forest', nationality: 'France', position: 'Forward' },
	{ name: 'diogo dalot', club: 'Manchester United', nationality: 'Portugal', position: 'Defender' },
	{ name: 'djed spence', club: 'Tottenham', nationality: 'England', position: 'Defender' },
	{ name: 'dominic calvert-lewin', club: 'Leeds United', nationality: 'England', position: 'Forward' },
	{ name: 'dominic solanke', club: 'Tottenham', nationality: 'England', position: 'Forward' },
	{ name: 'dominik szoboszlai', club: 'Liverpool', nationality: 'Hungary', position: 'Midfielder' },
	{ name: 'đorđe petrović', club: 'Bournemouth', nationality: 'Serbia', position: 'Goalkeeper' },
	{ name: 'douglas luiz', club: 'Aston Villa', nationality: 'Brazil', position: 'Midfielder' },
	{ name: 'dwight mcneil', club: 'Everton', nationality: 'England', position: 'Forward' },
	{ name: 'eberechi eze', club: 'Arsenal', nationality: 'England', position: 'Midfielder' },
	{ name: 'eddie nketiah', club: 'Crystal Palace', nationality: 'England', position: 'Forward' },
	{ name: 'el hadji diouf', club: 'West Ham', nationality: 'Senegal', position: 'Defender' },
	{ name: 'eli kroupi', club: 'Bournemouth', nationality: 'France', position: 'Forward' },
	{ name: 'eliezer mayenda', club: 'Sunderland', nationality: 'Spain', position: 'Forward' },
	{ name: 'ellery balcombe', club: 'Brentford', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'elliot anderson', club: 'Nottingham Forest', nationality: 'England', position: 'Midfielder' },
	{ name: 'ellis clark', club: 'Burnley', nationality: 'Scotland', position: 'Midfielder' },
	{ name: 'emil krafth', club: 'Newcastle', nationality: 'Sweden', position: 'Right-Back' },
	{ name: 'emile smith rowe', club: 'Fulham', nationality: 'England', position: 'Midfielder' },
	{ name: 'emiliano buendía', club: 'Aston Villa', nationality: 'Argentina', position: 'Midfielder' },
	{ name: 'emiliano martínez', club: 'Aston Villa', nationality: 'Argentina', position: 'Goalkeeper' },
	{ name: 'enes ünal', club: 'Bournemouth', nationality: 'Turkey', position: 'Forward' },
	{ name: 'enock agyei', club: 'Burnley', nationality: 'Belgium', position: 'Midfielder' },
	{ name: 'enso gonzalez', club: 'Wolverhampton', nationality: 'Paraguay', position: 'Forward' },
	{ name: 'enzo fernández', club: 'Chelsea', nationality: 'Argentina', position: 'Midfielder' },
	{ name: 'enzo le fée', club: 'Sunderland', nationality: 'France', position: 'Midfielder' },
	{ name: 'eric da silva moreira', club: 'Nottingham Forest', nationality: 'Germany', position: 'Defender' },
	{ name: 'erling haaland', club: 'Manchester City', nationality: 'Norway', position: 'Forward' },
	{ name: 'estevao', club: 'Chelsea', nationality: 'Brazil', position: 'Forward' },
	{ name: 'ethan ampadu', club: 'Leeds United', nationality: 'Wales', position: 'Midfielder' },
	{ name: 'ethan pinnock', club: 'Brentford', nationality: 'Jamaica', position: 'Defender' },
	{ name: 'ethan sutherland', club: 'Wolverhampton', nationality: 'Scotland', position: 'Midfielder' },
	{ name: 'evanilson', club: 'Bournemouth', nationality: 'Brazil', position: 'Forward' },
	{ name: 'evann guessand', club: 'Crystal Palace', nationality: 'Ivory Coast', position: 'Forward' },
	{ name: 'ezra mayers', club: 'West Ham', nationality: 'England', position: 'Defender' },
	{ name: 'ezri konsa', club: 'Aston Villa', nationality: 'England', position: 'Defender' },
	{ name: 'fabian schär', club: 'Newcastle', nationality: 'Switzerland', position: 'Defender' },
	{ name: 'fabio carvalho', club: 'Brentford', nationality: 'Portugal', position: 'Midfielder' },
	{ name: 'facundo buonanotte', club: 'Leeds United', nationality: 'Argentina', position: 'Midfielder' },
	{ name: 'federico chiesa', club: 'Liverpool', nationality: 'Italy', position: 'Forward' },
	{ name: 'ferdi kadıoğlu', club: 'Brighton & Hove Albion', nationality: 'Turkey', position: 'Defender' },
	{ name: 'filip jörgensen', club: 'Chelsea', nationality: 'Denmark', position: 'Goalkeeper' },
	{ name: 'finlay herrick', club: 'West Ham', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'finn geragusyan', club: 'Sunderland', nationality: 'Armenia', position: 'Forward' },
	{ name: 'florentino', club: 'Burnley', nationality: 'Portugal', position: 'Midfielder' },
	{ name: 'florian wirtz', club: 'Liverpool', nationality: 'Germany', position: 'Midfielder' },
	{ name: 'floyd samba', club: 'Manchester City', nationality: 'France', position: 'Defender' },
	{ name: 'fraser forster', club: 'Bournemouth', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'freddie potts', club: 'West Ham', nationality: 'England', position: 'Midfielder' },
	{ name: 'freddie simmonds', club: 'Brighton & Hove Albion', nationality: 'England', position: 'Defender' },
	{ name: 'freddie woodman', club: 'Liverpool', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'gabriel gudmundsson', club: 'Leeds United', nationality: 'Sweden', position: 'Defender' },
	{ name: 'gabriel jesus', club: 'Arsenal', nationality: 'Brazil', position: 'Forward' },
	{ name: 'gabriel magalhães', club: 'Arsenal', nationality: 'Brazil', position: 'Defender' },
	{ name: 'gabriel slonina', club: 'Chelsea', nationality: 'USA', position: 'Goalkeeper' },
	{ name: 'george brierley', club: 'Burnley', nationality: 'England', position: 'Midfielder' },
	{ name: 'george hemmings', club: 'Aston Villa', nationality: 'England', position: 'Forward' },
	{ name: 'george king', club: 'Crystal Palace', nationality: 'England', position: 'Defender' },
	{ name: 'georginio rutter', club: 'Brighton & Hove Albion', nationality: 'France', position: 'Forward' },
	{ name: 'gianluigi donnarumma', club: 'Manchester City', nationality: 'Italy', position: 'Goalkeeper' },
	{ name: 'giorgi mamardashvili', club: 'Liverpool', nationality: 'Georgia', position: 'Goalkeeper' },
	{ name: 'giovanni leoni', club: 'Liverpool', nationality: 'Italy', position: 'Defender' },
	{ name: 'godwill kukonki', club: 'Manchester United', nationality: 'England', position: 'Defender' },
	{ name: 'granit xhaka', club: 'Sunderland', nationality: 'Switzerland', position: 'Midfielder' },
	{ name: 'guglielmo vicario', club: 'Tottenham', nationality: 'Italy', position: 'Goalkeeper' },
	{ name: 'habib diarra', club: 'Sunderland', nationality: 'Senegal', position: 'Midfielder' },
	{ name: 'hákon rafn valdimarsson', club: 'Brentford', nationality: 'Iceland', position: 'Goalkeeper' },
	{ name: 'hannibal mejbri', club: 'Burnley', nationality: 'Tunisia', position: 'Midfielder' },
	{ name: 'harrison armstrong', club: 'Everton', nationality: 'England', position: 'Midfielder' },
	{ name: 'harrison dudziak', club: 'Arsenal', nationality: 'England', position: 'Midfielder' },
	{ name: 'harrison jones', club: 'Sunderland', nationality: 'England', position: 'Midfielder' },
	{ name: 'harrison reed', club: 'Fulham', nationality: 'England', position: 'Midfielder' },
	{ name: 'harry howell', club: 'Brighton & Hove Albion', nationality: 'England', position: 'Forward' },
	{ name: 'harry maguire', club: 'Manchester United', nationality: 'England', position: 'Defender' },
	{ name: 'harry wilson', club: 'Fulham', nationality: 'Wales', position: 'Forward' },
	{ name: 'harvey barnes', club: 'Newcastle', nationality: 'England', position: 'Forward' },
	{ name: 'harvey davies', club: 'Liverpool', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'harvey elliott', club: 'Aston Villa', nationality: 'England', position: 'Midfielder' },
	{ name: 'hjalmar ekdal', club: 'Burnley', nationality: 'Sweden', position: 'Defender' },
	{ name: 'hugo bueno', club: 'Wolverhampton', nationality: 'Spain', position: 'Defender' },
	{ name: 'hugo ekitike', club: 'Liverpool', nationality: 'France', position: 'Forward' },
	{ name: 'hwang heechan', club: 'Wolverhampton', nationality: 'South Korea', position: 'Forward' },
	{ name: 'ian maatsen', club: 'Aston Villa', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'ibrahim sangaré', club: 'Nottingham Forest', nationality: 'Ivory Coast', position: 'Midfielder' },
	{ name: 'ibrahima konaté', club: 'Liverpool', nationality: 'France', position: 'Defender' },
	{ name: 'idrissa gana guèye', club: 'Everton', nationality: 'Senegal', position: 'Midfielder' },
	{ name: 'ifeoluwa ibrahim', club: 'Arsenal', nationality: 'England', position: 'Midfielder' },
	{ name: 'igor jesus', club: 'Nottingham Forest', nationality: 'Brazil', position: 'Forward' },
	{ name: 'igor julio', club: 'Brighton & Hove Albion', nationality: 'Brazil', position: 'Defender' },
	{ name: 'ilia gruev', club: 'Leeds United', nationality: 'Bulgaria', position: 'Midfielder' },
	{ name: 'iliman ndiaye', club: 'Everton', nationality: 'Senegal', position: 'Forward' },
	{ name: 'illan meslier', club: 'Leeds United', nationality: 'France', position: 'Goalkeeper' },
	{ name: 'ismaïla sarr', club: 'Crystal Palace', nationality: 'Senegal', position: 'Forward' },
	{ name: 'issa diop', club: 'Fulham', nationality: 'France', position: 'Defender' },
	{ name: 'jack fletcher', club: 'Manchester United', nationality: 'England', position: 'Midfielder' },
	{ name: 'jack grealish', club: 'Everton', nationality: 'England', position: 'Forward' },
	{ name: 'jack hinshelwood', club: 'Brighton & Hove Albion', nationality: 'England', position: 'Midfielder' },
	{ name: 'jack moorhouse', club: 'Manchester United', nationality: 'Ireland', position: 'Midfielder' },
	{ name: 'jack porter', club: 'Arsenal', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'jack whittaker', club: 'Sunderland', nationality: 'England', position: 'Midfielder' },
	{ name: 'jackson izquierdo', club: 'Crystal Palace', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'jackson tchatchoua', club: 'Wolverhampton', nationality: 'Cameroon', position: 'Forward' },
	{ name: 'jacob bruun larsen', club: 'Burnley', nationality: 'Denmark', position: 'Forward' },
	{ name: 'jacob murphy', club: 'Newcastle', nationality: 'England', position: 'Forward' },
	{ name: 'jacob ramsey', club: 'Newcastle', nationality: 'England', position: 'Midfielder' },
	{ name: 'jaden dixon', club: 'Arsenal', nationality: 'England', position: 'Defender' },
	{ name: 'jadon sancho', club: 'Aston Villa', nationality: 'England', position: 'Left Winger' },
	{ name: 'jaidon anthony', club: 'Burnley', nationality: 'England', position: 'Forward' },
	{ name: 'jair paula', club: 'Nottingham Forest', nationality: 'Brazil', position: 'Defender' },
	{ name: 'jaka bijol', club: 'Leeds United', nationality: 'Slovenia', position: 'Defender' },
	{ name: 'jake o\'brien', club: 'Everton', nationality: 'Ireland', position: 'Defender' },
	{ name: 'james garner', club: 'Everton', nationality: 'England', position: 'Midfielder' },
	{ name: 'james hill', club: 'Bournemouth', nationality: 'England', position: 'Defender' },
	{ name: 'james hillson', club: 'Chelsea', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'james justin', club: 'Leeds United', nationality: 'England', position: 'Defender' },
	{ name: 'james maddison', club: 'Tottenham', nationality: 'England', position: 'Midfielder' },
	{ name: 'james mcatee', club: 'Nottingham Forest', nationality: 'England', position: 'Midfielder' },
	{ name: 'james mcconnell', club: 'Liverpool', nationality: 'England', position: 'Central Midfield' },
	{ name: 'james milner', club: 'Brighton & Hove Albion', nationality: 'England', position: 'Central Midfield' },
	{ name: 'james rowswell', club: 'Tottenham', nationality: 'England', position: 'Defender' },
	{ name: 'james tarkowski', club: 'Everton', nationality: 'England', position: 'Defender' },
	{ name: 'james trafford', club: 'Manchester City', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'james ward-prowse', club: 'Burnley', nationality: 'England', position: 'Midfielder' },
	{ name: 'james wilson', club: 'Tottenham', nationality: 'Scotland', position: 'Forward' },
	{ name: 'james wright', club: 'Aston Villa', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'jamie bynoe-gittens', club: 'Chelsea', nationality: 'England', position: 'Forward' },
	{ name: 'jan paul van hecke', club: 'Brighton & Hove Albion', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'jarrad branthwaite', club: 'Everton', nationality: 'England', position: 'Defender' },
	{ name: 'jarrod bowen', club: 'West Ham', nationality: 'England', position: 'Forward' },
	{ name: 'jason steele', club: 'Brighton & Hove Albion', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'jaydee canvot', club: 'Crystal Palace', nationality: 'France', position: 'Defender' },
	{ name: 'jayden bogle', club: 'Leeds United', nationality: 'England', position: 'Defender' },
	{ name: 'jayden danns', club: 'Liverpool', nationality: 'England', position: 'Centre-Forward' },
	{ name: 'jayden lienou', club: 'Leeds United', nationality: 'Wales', position: 'Left-Back' },
	{ name: 'jaydon jones', club: 'Sunderland', nationality: 'England', position: 'Midfielder' },
	{ name: 'jean-clair todibo', club: 'West Ham', nationality: 'France', position: 'Defender' },
	{ name: 'jean-philippe mateta', club: 'Crystal Palace', nationality: 'France', position: 'Forward' },
	{ name: 'jean-ricner bellegarde', club: 'Wolverhampton', nationality: 'Haiti', position: 'Midfielder' },
	{ name: 'jefferson lerma', club: 'Crystal Palace', nationality: 'Colombia', position: 'Midfielder' },
	{ name: 'jenson jones', club: 'Sunderland', nationality: 'England', position: 'Defender' },
	{ name: 'jeremie frimpong', club: 'Liverpool', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'jeremy doku', club: 'Manchester City', nationality: 'Belgium', position: 'Forward' },
	{ name: 'jerome abbey', club: 'Wolverhampton', nationality: 'England', position: 'Midfielder' },
	{ name: 'jesse derry', club: 'Chelsea', nationality: 'England', position: 'Forward' },
	{ name: 'jim thwaites', club: 'Manchester United', nationality: 'England', position: 'Midfielder' },
	{ name: 'jimmy sinclair', club: 'Nottingham Forest', nationality: 'England', position: 'Midfielder' },
	{ name: 'joachim andersen', club: 'Fulham', nationality: 'Denmark', position: 'Defender' },
	{ name: 'joão gomes', club: 'Wolverhampton', nationality: 'Brazil', position: 'Midfielder' },
	{ name: 'joão palhinha', club: 'Tottenham', nationality: 'Portugal', position: 'Midfielder' },
	{ name: 'joão pedro', club: 'Chelsea', nationality: 'Brazil', position: 'Forward' },
	{ name: 'jocelin bi', club: 'Sunderland', nationality: 'Ivory Coast', position: 'Forward' },
	{ name: 'joe gomez', club: 'Liverpool', nationality: 'England', position: 'Defender' },
	{ name: 'joe rodon', club: 'Leeds United', nationality: 'Wales', position: 'Defender' },
	{ name: 'joe white', club: 'Newcastle', nationality: 'England', position: 'Midfielder' },
	{ name: 'joe willock', club: 'Newcastle', nationality: 'England', position: 'Midfielder' },
	{ name: 'joe worrall', club: 'Burnley', nationality: 'England', position: 'Defender' },
	{ name: 'joel drakes-thomas', club: 'Crystal Palace', nationality: 'England', position: 'Midfielder' },
	{ name: 'joël piroe', club: 'Leeds United', nationality: 'Netherlands', position: 'Forward' },
	{ name: 'joël veltman', club: 'Brighton & Hove Albion', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'joelinton', club: 'Newcastle', nationality: 'Brazil', position: 'Midfielder' },
	{ name: 'john', club: 'Nottingham Forest', nationality: 'Brazil', position: 'Goalkeeper' },
	{ name: 'john mcginn', club: 'Aston Villa', nationality: 'Scotland', position: 'Midfielder' },
	{ name: 'john ruddy', club: 'Newcastle', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'john stones', club: 'Manchester City', nationality: 'England', position: 'Defender' },
	{ name: 'jonah kusi-asare', club: 'Fulham', nationality: 'Sweden', position: 'Forward' },
	{ name: 'jordan henderson', club: 'Brentford', nationality: 'England', position: 'Midfielder' },
	{ name: 'jordan pickford', club: 'Everton', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'jorge cuenca', club: 'Fulham', nationality: 'Spain', position: 'Defender' },
	{ name: 'jørgen strand larsen', club: 'Crystal Palace', nationality: 'Norway', position: 'Forward' },
	{ name: 'jorrel hato', club: 'Chelsea', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'josé sá', club: 'Wolverhampton', nationality: 'Portugal', position: 'Goalkeeper' },
	{ name: 'josh acheampong', club: 'Chelsea', nationality: 'England', position: 'Defender' },
	{ name: 'josh cullen', club: 'Burnley', nationality: 'Ireland', position: 'Midfielder' },
	{ name: 'josh dasilva', club: 'Brentford', nationality: 'England', position: 'Midfielder' },
	{ name: 'josh gracey', club: 'Wolverhampton', nationality: 'Northern Ireland', position: 'Goalkeeper' },
	{ name: 'josh laurent', club: 'Burnley', nationality: 'England', position: 'Midfielder' },
	{ name: 'josh nichols', club: 'Arsenal', nationality: 'England', position: 'Defender' },
	{ name: 'josh stephenson', club: 'Brentford', nationality: 'England', position: 'Midfielder' },
	{ name: 'joshua ajala', club: 'West Ham', nationality: 'England', position: 'Forward' },
	{ name: 'joshua king', club: 'Fulham', nationality: 'England', position: 'Midfielder' },
	{ name: 'joshua zirkzee', club: 'Manchester United', nationality: 'Netherlands', position: 'Forward' },
	{ name: 'joško gvardiol', club: 'Manchester City', nationality: 'Croatia', position: 'Defender' },
	{ name: 'julian eyestone', club: 'Brentford', nationality: 'USA', position: 'Goalkeeper' },
	{ name: 'julio soler', club: 'Bournemouth', nationality: 'Argentina', position: 'Defender' },
	{ name: 'jun\'ai byfield', club: 'Tottenham', nationality: 'England', position: 'Defender' },
	{ name: 'jurrien timber', club: 'Arsenal', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'justin devenny', club: 'Crystal Palace', nationality: 'Northern Ireland', position: 'Midfielder' },
	{ name: 'justin hanks', club: 'Nottingham Forest', nationality: 'England', position: 'Defender' },
	{ name: 'justin kluivert', club: 'Bournemouth', nationality: 'Netherlands', position: 'Midfielder' },
	{ name: 'kaden braithwaite', club: 'Manchester City', nationality: 'England', position: 'Defender' },
	{ name: 'kaden rodney', club: 'Crystal Palace', nationality: 'England', position: 'Defensive Midfield' },
	{ name: 'kai havertz', club: 'Arsenal', nationality: 'Germany', position: 'Forward' },
	{ name: 'kaide gordon', club: 'Liverpool', nationality: 'England', position: 'Right Winger' },
	{ name: 'kaoru mitoma', club: 'Brighton & Hove Albion', nationality: 'Japan', position: 'Forward' },
	{ name: 'karl darlow', club: 'Leeds United', nationality: 'Wales', position: 'Goalkeeper' },
	{ name: 'kaye furo', club: 'Brentford', nationality: 'Belgium', position: 'Forward' },
	{ name: 'keane lewis-potter', club: 'Brentford', nationality: 'England', position: 'Midfielder' },
	{ name: 'keehan willows', club: 'Nottingham Forest', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'keiber lamadrid', club: 'West Ham', nationality: 'Venezuela', position: 'Forward' },
	{ name: 'kenny tete', club: 'Fulham', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'kepa arrizabalaga', club: 'Arsenal', nationality: 'Spain', position: 'Goalkeeper' },
	{ name: 'kevin danso', club: 'Tottenham', nationality: 'Austria', position: 'Defender' },
	{ name: 'kevin santos', club: 'Fulham', nationality: 'Brazil', position: 'Forward' },
	{ name: 'kevin schade', club: 'Brentford', nationality: 'Germany', position: 'Forward' },
	{ name: 'keyrol figueroa', club: 'Liverpool', nationality: 'USA', position: 'Forward' },
	{ name: 'khari ranson', club: 'Arsenal', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'kian brown', club: 'Burnley', nationality: 'Ireland', position: 'Midfielder' },
	{ name: 'kian noble', club: 'Manchester City', nationality: 'England', position: 'Defender' },
	{ name: 'kieran morrison', club: 'Liverpool', nationality: 'Northern Ireland', position: 'Forward' },
	{ name: 'kieran trippier', club: 'Newcastle', nationality: 'England', position: 'Defender' },
	{ name: 'kiernan dewsbury hall', club: 'Everton', nationality: 'England', position: 'Midfielder' },
	{ name: 'kobbie mainoo', club: 'Manchester United', nationality: 'England', position: 'Midfielder' },
	{ name: 'konstantinos mavropanos', club: 'West Ham', nationality: 'Greece', position: 'Defender' },
	{ name: 'kornel miściur', club: 'Liverpool', nationality: 'Poland', position: 'Goalkeeper' },
	{ name: 'kristoffer ajer', club: 'Brentford', nationality: 'Norway', position: 'Defender' },
	{ name: 'kyle walker', club: 'Burnley', nationality: 'England', position: 'Defender' },
	{ name: 'kyle walker-peters', club: 'West Ham', nationality: 'England', position: 'Defender' },
	{ name: 'lamare bogarde', club: 'Aston Villa', nationality: 'Netherlands', position: 'Midfielder' },
	{ name: 'lamin sillah', club: 'Nottingham Forest', nationality: 'Gambia', position: 'Forward' },
	{ name: 'landon emenalo', club: 'Chelsea', nationality: 'England', position: 'Defender' },
	{ name: 'leandro trossard', club: 'Arsenal', nationality: 'Belgium', position: 'Forward' },
	{ name: 'leny yoro', club: 'Manchester United', nationality: 'France', position: 'Defender' },
	{ name: 'leo shahar', club: 'Newcastle', nationality: 'England', position: 'Defender' },
	{ name: 'leon bailey', club: 'Aston Villa', nationality: 'Jamaica', position: 'Forward' },
	{ name: 'leon routh', club: 'Aston Villa', nationality: 'England', position: 'Defender' },
	{ name: 'levi colwill', club: 'Chelsea', nationality: 'England', position: 'Defender' },
	{ name: 'lewis cook', club: 'Bournemouth', nationality: 'England', position: 'Midfielder' },
	{ name: 'lewis dunk', club: 'Brighton & Hove Albion', nationality: 'England', position: 'Defender' },
	{ name: 'lewis miley', club: 'Newcastle', nationality: 'England', position: 'Midfielder' },
	{ name: 'lewis orford', club: 'West Ham', nationality: 'England', position: 'Midfielder' },
	{ name: 'liam delap', club: 'Chelsea', nationality: 'England', position: 'Forward' },
	{ name: 'lisandro martínez', club: 'Manchester United', nationality: 'Argentina', position: 'Defender' },
	{ name: 'lorenzo lucca', club: 'Nottingham Forest', nationality: 'Italy', position: 'Forward' },
	{ name: 'louis beyer', club: 'Burnley', nationality: 'Germany', position: 'Defender' },
	{ name: 'loum tchaouna', club: 'Burnley', nationality: 'France', position: 'Forward' },
	{ name: 'luca gunter', club: 'Tottenham', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'luca netz', club: 'Nottingham Forest', nationality: 'Germany', position: 'Defender' },
	{ name: 'luca williams-barnett', club: 'Tottenham', nationality: 'England', position: 'Forward' },
	{ name: 'lucas bergvall', club: 'Tottenham', nationality: 'Sweden', position: 'Midfielder' },
	{ name: 'lucas digne', club: 'Aston Villa', nationality: 'France', position: 'Defender' },
	{ name: 'lucas perri', club: 'Leeds United', nationality: 'Brazil', position: 'Goalkeeper' },
	{ name: 'lucas pires', club: 'Burnley', nationality: 'Brazil', position: 'Defender' },
	{ name: 'luka bentt', club: 'Brentford', nationality: 'Belgium', position: 'Midfielder' },
	{ name: 'lukas nmecha', club: 'Leeds United', nationality: 'Germany', position: 'Forward' },
	{ name: 'łukasz fabiański', club: 'West Ham', nationality: 'Poland', position: 'Goalkeeper' },
	{ name: 'luke o\'nien', club: 'Sunderland', nationality: 'England', position: 'Defender' },
	{ name: 'luke rawlings', club: 'Wolverhampton', nationality: 'England', position: 'Midfielder' },
	{ name: 'luke shaw', club: 'Manchester United', nationality: 'England', position: 'Defender' },
	{ name: 'lutsharel geertruida', club: 'Sunderland', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'lyle foster', club: 'Burnley', nationality: 'South Africa', position: 'Forward' },
	{ name: 'mads hermansen', club: 'West Ham', nationality: 'Denmark', position: 'Goalkeeper' },
	{ name: 'malachi hardy', club: 'Tottenham', nationality: 'England', position: 'Defender' },
	{ name: 'malcom dacosta', club: 'Bournemouth', nationality: 'Ecuador', position: 'Forward' },
	{ name: 'malick thiaw', club: 'Newcastle', nationality: 'Germany', position: 'Defender' },
	{ name: 'malick yalcouyé', club: 'Brighton & Hove Albion', nationality: 'Mali', position: 'Midfielder' },
	{ name: 'malik olayiwola', club: 'Everton', nationality: 'England', position: 'Midfielder' },
	{ name: 'malo gusto', club: 'Chelsea', nationality: 'France', position: 'Defender' },
	{ name: 'mamadou sarr', club: 'Chelsea', nationality: 'Senegal', position: 'Defender' },
	{ name: 'manuel ugarte', club: 'Manchester United', nationality: 'Uruguay', position: 'Midfielder' },
	{ name: 'marc guéhi', club: 'Manchester City', nationality: 'England', position: 'Defender' },
	{ name: 'marc guiu', club: 'Chelsea', nationality: 'Spain', position: 'Forward' },
	{ name: 'marco bizot', club: 'Aston Villa', nationality: 'Netherlands', position: 'Goalkeeper' },
	{ name: 'marcos senesi', club: 'Bournemouth', nationality: 'Argentina', position: 'Defender' },
	{ name: 'marcus bettinelli', club: 'Manchester City', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'marcus edwards', club: 'Burnley', nationality: 'England', position: 'Forward' },
	{ name: 'marcus tavernier', club: 'Bournemouth', nationality: 'England', position: 'Midfielder' },
	{ name: 'mark gillespie', club: 'Newcastle', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'mark travers', club: 'Everton', nationality: 'Ireland', position: 'Goalkeeper' },
	{ name: 'marli salmon', club: 'Arsenal', nationality: 'England', position: 'Defender' },
	{ name: 'martin dúbravka', club: 'Burnley', nationality: 'Slovakia', position: 'Goalkeeper' },
	{ name: 'martin ødegaard', club: 'Arsenal', nationality: 'Norway', position: 'Midfielder' },
	{ name: 'martín zubimendi', club: 'Arsenal', nationality: 'Spain', position: 'Midfielder' },
	{ name: 'martinelli', club: 'Arsenal', nationality: 'Brazil', position: 'Forward' },
	{ name: 'mason mount', club: 'Manchester United', nationality: 'England', position: 'Midfielder' },
	{ name: 'matai akinmboni', club: 'Bournemouth', nationality: 'USA', position: 'Defender' },
	{ name: 'mateo kovačić', club: 'Manchester City', nationality: 'Croatia', position: 'Midfielder' },
	{ name: 'mateus fernandes', club: 'West Ham', nationality: 'Portugal', position: 'Midfielder' },
	{ name: 'mateus mané', club: 'Wolverhampton', nationality: 'Portugal', position: 'Midfielder' },
	{ name: 'matheus cunha', club: 'Manchester United', nationality: 'Brazil', position: 'Forward' },
	{ name: 'matheus nunes', club: 'Manchester City', nationality: 'Portugal', position: 'Defender' },
	{ name: 'mathias jensen', club: 'Brentford', nationality: 'Denmark', position: 'Midfielder' },
	{ name: 'mathis eboué', club: 'Chelsea', nationality: 'England', position: 'Forward' },
	{ name: 'mathys tel', club: 'Tottenham', nationality: 'France', position: 'Forward' },
	{ name: 'mats wieffer', club: 'Brighton & Hove Albion', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'matt doherty', club: 'Wolverhampton', nationality: 'Ireland', position: 'Defender' },
	{ name: 'matt o\'riley', club: 'Brighton & Hove Albion', nationality: 'Denmark', position: 'Midfielder' },
	{ name: 'matthijs de ligt', club: 'Manchester United', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'matty cash', club: 'Aston Villa', nationality: 'Poland', position: 'Defender' },
	{ name: 'matz sels', club: 'Nottingham Forest', nationality: 'Belgium', position: 'Goalkeeper' },
	{ name: 'max alleyne', club: 'Manchester City', nationality: 'England', position: 'Defender' },
	{ name: 'max dowman', club: 'Arsenal', nationality: 'England', position: 'Forward' },
	{ name: 'max kilman', club: 'West Ham', nationality: 'England', position: 'Defender' },
	{ name: 'max merrick', club: 'Chelsea', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'max weiss', club: 'Burnley', nationality: 'Germany', position: 'Goalkeeper' },
	{ name: 'maxence lacroix', club: 'Crystal Palace', nationality: 'France', position: 'Defender' },
	{ name: 'maxim de cuyper', club: 'Brighton & Hove Albion', nationality: 'Belgium', position: 'Defender' },
	{ name: 'maxime estève', club: 'Burnley', nationality: 'France', position: 'Defender' },
	{ name: 'melker ellborg', club: 'Sunderland', nationality: 'Sweden', position: 'Goalkeeper' },
	{ name: 'merlin röhl', club: 'Everton', nationality: 'Germany', position: 'Midfielder' },
	{ name: 'michael kayode', club: 'Brentford', nationality: 'Italy', position: 'Defender' },
	{ name: 'michael keane', club: 'Everton', nationality: 'England', position: 'Defender' },
	{ name: 'michael laffey', club: 'Liverpool', nationality: 'England', position: 'Midfielder' },
	{ name: 'mickey van de ven', club: 'Tottenham', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'mike trésor', club: 'Burnley', nationality: 'Belgium', position: 'Midfielder' },
	{ name: 'mikel merino', club: 'Arsenal', nationality: 'Spain', position: 'Midfielder' },
	{ name: 'mikkel damsgaard', club: 'Brentford', nationality: 'Denmark', position: 'Midfielder' },
	{ name: 'milan aleksić', club: 'Sunderland', nationality: 'Serbia', position: 'Central Midfield' },
	{ name: 'milos kerkez', club: 'Liverpool', nationality: 'Hungary', position: 'Defender' },
	{ name: 'mohamadou kante', club: 'West Ham', nationality: 'France', position: 'Midfielder' },
	{ name: 'mohamed koné', club: 'Aston Villa', nationality: 'Ivory Coast', position: 'Midfielder' },
	{ name: 'mohamed salah', club: 'Liverpool', nationality: 'Egypt', position: 'Forward' },
	{ name: 'mohammed kudus', club: 'Tottenham', nationality: 'Ghana', position: 'Forward' },
	{ name: 'moisés caicedo', club: 'Chelsea', nationality: 'Ecuador', position: 'Midfielder' },
	{ name: 'mor talla n\'diaye', club: 'Liverpool', nationality: 'Senegal', position: 'Defender' },
	{ name: 'morato', club: 'Nottingham Forest', nationality: 'Brazil', position: 'Defender' },
	{ name: 'morgan gibbs-white', club: 'Nottingham Forest', nationality: 'England', position: 'Midfielder' },
	{ name: 'morgan rogers', club: 'Aston Villa', nationality: 'England', position: 'Midfielder' },
	{ name: 'murillo', club: 'Nottingham Forest', nationality: 'Brazil', position: 'Defender' },
	{ name: 'murray campbell', club: 'Burnley', nationality: 'Scotland', position: 'Defender' },
	{ name: 'mykhailo mudryk', club: 'Chelsea', nationality: 'Ukraine', position: 'Forward' },
	{ name: 'myles lewis-skelly', club: 'Arsenal', nationality: 'England', position: 'Defender' },
	{ name: 'nathan aké', club: 'Manchester City', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'nathan collins', club: 'Brentford', nationality: 'Ireland', position: 'Defender' },
	{ name: 'nathan fraser', club: 'Wolverhampton', nationality: 'England', position: 'Forward' },
	{ name: 'nathan patterson', club: 'Everton', nationality: 'Scotland', position: 'Defender' },
	{ name: 'nathaniel clyne', club: 'Crystal Palace', nationality: 'England', position: 'Defender' },
	{ name: 'neco williams', club: 'Nottingham Forest', nationality: 'Wales', position: 'Defender' },
	{ name: 'nehemiah oriola', club: 'Brighton & Hove Albion', nationality: 'England', position: 'Midfielder' },
	{ name: 'nick pope', club: 'Newcastle', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'nick woltemade', club: 'Newcastle', nationality: 'Germany', position: 'Forward' },
	{ name: 'nico gonzalez', club: 'Manchester City', nationality: 'Spain', position: 'Midfielder' },
	{ name: 'nico o\'reilly', club: 'Manchester City', nationality: 'England', position: 'Defender' },
	{ name: 'nicolás domínguez', club: 'Nottingham Forest', nationality: 'Argentina', position: 'Midfielder' },
	{ name: 'nicolò savona', club: 'Nottingham Forest', nationality: 'Italy', position: 'Defender' },
	{ name: 'nikola milenković', club: 'Nottingham Forest', nationality: 'Serbia', position: 'Defender' },
	{ name: 'nils ramming', club: 'Brighton & Hove Albion', nationality: 'Sweden', position: 'Goalkeeper' },
	{ name: 'nilson angulo', club: 'Sunderland', nationality: 'Ecuador', position: 'Forward' },
	{ name: 'noah okafor', club: 'Leeds United', nationality: 'Switzerland', position: 'Forward' },
	{ name: 'noah sadiki', club: 'Sunderland', nationality: 'Congo DR', position: 'Midfielder' },
	{ name: 'noni madueke', club: 'Arsenal', nationality: 'England', position: 'Forward' },
	{ name: 'nordi mukiele', club: 'Sunderland', nationality: 'France', position: 'Defender' },
	{ name: 'noussair mazraoui', club: 'Manchester United', nationality: 'Morocco', position: 'Defender' },
	{ name: 'ola aina', club: 'Nottingham Forest', nationality: 'Nigeria', position: 'Defender' },
	{ name: 'oliver pimlott', club: 'Burnley', nationality: 'England', position: 'Midfielder' },
	{ name: 'oliver scarles', club: 'West Ham', nationality: 'England', position: 'Defender' },
	{ name: 'olivier boscagli', club: 'Brighton & Hove Albion', nationality: 'France', position: 'Defender' },
	{ name: 'ollie harrison', club: 'Chelsea', nationality: 'England', position: 'Midfielder' },
	{ name: 'ollie shield', club: 'Brentford', nationality: 'England', position: 'Midfielder' },
	{ name: 'ollie watkins', club: 'Aston Villa', nationality: 'England', position: 'Forward' },
	{ name: 'omar alderete', club: 'Sunderland', nationality: 'Paraguay', position: 'Defender' },
	{ name: 'omar marmoush', club: 'Manchester City', nationality: 'Egypt', position: 'Forward' },
	{ name: 'omari hutchinson', club: 'Nottingham Forest', nationality: 'England', position: 'Forward' },
	{ name: 'oscar bobb', club: 'Fulham', nationality: 'Norway', position: 'Forward' },
	{ name: 'pablo felipe', club: 'West Ham', nationality: 'Brazil', position: 'Forward' },
	{ name: 'pape sarr', club: 'Tottenham', nationality: 'Senegal', position: 'Midfielder' },
	{ name: 'pascal groß', club: 'Brighton & Hove Albion', nationality: 'Germany', position: 'Midfielder' },
	{ name: 'pascal struijk', club: 'Leeds United', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'patrick dorgu', club: 'Manchester United', nationality: 'Denmark', position: 'Forward' },
	{ name: 'pau torres', club: 'Aston Villa', nationality: 'Spain', position: 'Defender' },
	{ name: 'pedro lima', club: 'Wolverhampton', nationality: 'Brazil', position: 'Defender' },
	{ name: 'pedro neto', club: 'Chelsea', nationality: 'Portugal', position: 'Forward' },
	{ name: 'pedro porro', club: 'Tottenham', nationality: 'Spain', position: 'Defender' },
	{ name: 'phil foden', club: 'Manchester City', nationality: 'England', position: 'Midfielder' },
	{ name: 'piero hincapié', club: 'Arsenal', nationality: 'Ecuador', position: 'Defender' },
	{ name: 'quilindschy hartman', club: 'Burnley', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'radu drăgușin', club: 'Tottenham', nationality: 'Romania', position: 'Defender' },
	{ name: 'randal kolo muani', club: 'Tottenham', nationality: 'France', position: 'Forward' },
	{ name: 'raúl jiménez', club: 'Fulham', nationality: 'Mexico', position: 'Forward' },
	{ name: 'rayan', club: 'Bournemouth', nationality: 'Brazil', position: 'Forward' },
	{ name: 'rayan aït nouri', club: 'Manchester City', nationality: 'Algeria', position: 'Defender' },
	{ name: 'rayan cherki', club: 'Manchester City', nationality: 'France', position: 'Midfielder' },
	{ name: 'reece james', club: 'Chelsea', nationality: 'England', position: 'Defender' },
	{ name: 'reece welch', club: 'Everton', nationality: 'England', position: 'Defender' },
	{ name: 'reggie walsh', club: 'Chelsea', nationality: 'England', position: 'Midfielder' },
	{ name: 'reigan heskey', club: 'Manchester City', nationality: 'England', position: 'Forward' },
	{ name: 'reinildo', club: 'Sunderland', nationality: 'Mozambique', position: 'Defender' },
	{ name: 'reiss nelson', club: 'Brentford', nationality: 'England', position: 'Forward' },
	{ name: 'remi matthews', club: 'Crystal Palace', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'remy rees-dottin', club: 'Bournemouth', nationality: 'England', position: 'Forward' },
	{ name: 'rhys chadwick', club: 'Leeds United', nationality: 'England', position: 'Attacking Midfield' },
	{ name: 'rhys williams', club: 'Liverpool', nationality: 'England', position: 'Centre-Back' },
	{ name: 'riccardo calafiori', club: 'Arsenal', nationality: 'Italy', position: 'Defender' },
	{ name: 'richarlison', club: 'Tottenham', nationality: 'Brazil', position: 'Forward' },
	{ name: 'rico henry', club: 'Brentford', nationality: 'Jamaica', position: 'Defender' },
	{ name: 'rico lewis', club: 'Manchester City', nationality: 'England', position: 'Defender' },
	{ name: 'riley owen', club: 'Brentford', nationality: 'England', position: 'Midfielder' },
	{ name: 'rio cardines', club: 'Crystal Palace', nationality: 'Trinidad & Tobago', position: 'Defender' },
	{ name: 'rio kyerematen', club: 'Tottenham', nationality: 'England', position: 'Midfielder' },
	{ name: 'rio ngumoha', club: 'Liverpool', nationality: 'England', position: 'Forward' },
	{ name: 'robert sánchez', club: 'Chelsea', nationality: 'Spain', position: 'Goalkeeper' },
	{ name: 'robin roefs', club: 'Sunderland', nationality: 'Netherlands', position: 'Goalkeeper' },
	{ name: 'rodri', club: 'Manchester City', nationality: 'Spain', position: 'Midfielder' },
	{ name: 'rodrigo bentancur', club: 'Tottenham', nationality: 'Uruguay', position: 'Midfielder' },
	{ name: 'rodrigo gomes', club: 'Wolverhampton', nationality: 'Portugal', position: 'Forward' },
	{ name: 'rodrigo muniz', club: 'Fulham', nationality: 'Brazil', position: 'Forward' },
	{ name: 'romaine mundle', club: 'Sunderland', nationality: 'England', position: 'Forward' },
	{ name: 'romelle donovan', club: 'Brentford', nationality: 'England', position: 'Forward' },
	{ name: 'romeo lavia', club: 'Chelsea', nationality: 'Belgium', position: 'Midfielder' },
	{ name: 'ronnie hollingshead', club: 'Aston Villa', nationality: 'Wales', position: 'Goalkeeper' },
	{ name: 'ross barkley', club: 'Aston Villa', nationality: 'England', position: 'Midfielder' },
	{ name: 'rúben dias', club: 'Manchester City', nationality: 'Portugal', position: 'Defender' },
	{ name: 'russ oakley', club: 'Aston Villa', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'ryan christie', club: 'Bournemouth', nationality: 'Scotland', position: 'Midfielder' },
	{ name: 'ryan gravenberch', club: 'Liverpool', nationality: 'Netherlands', position: 'Midfielder' },
	{ name: 'ryan kavuma-mcqueen', club: 'Chelsea', nationality: 'England', position: 'Forward' },
	{ name: 'ryan mcaidoo', club: 'Manchester City', nationality: 'England', position: 'Forward' },
	{ name: 'ryan sessegnon', club: 'Fulham', nationality: 'England', position: 'Defender' },
	{ name: 'ryan yates', club: 'Nottingham Forest', nationality: 'England', position: 'Midfielder' },
	{ name: 'saheed olagunju', club: 'Wolverhampton', nationality: 'England', position: 'Defender' },
	{ name: 'sam alabi', club: 'Newcastle', nationality: 'England', position: 'Midfielder' },
	{ name: 'sam amissah', club: 'Fulham', nationality: 'England', position: 'Defender' },
	{ name: 'sam byram', club: 'Leeds United', nationality: 'England', position: 'Defender' },
	{ name: 'sam chambers', club: 'Leeds United', nationality: 'Scotland', position: 'Midfielder' },
	{ name: 'sam johnstone', club: 'Wolverhampton', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'sam proctor', club: 'Aston Villa', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'samuel chukwueze', club: 'Fulham', nationality: 'Nigeria', position: 'Forward' },
	{ name: 'sander berge', club: 'Fulham', nationality: 'Norway', position: 'Midfielder' },
	{ name: 'sandro tonali', club: 'Newcastle', nationality: 'Italy', position: 'Midfielder' },
	{ name: 'santiago bueno', club: 'Wolverhampton', nationality: 'Uruguay', position: 'Defender' },
	{ name: 'saša lukić', club: 'Fulham', nationality: 'Serbia', position: 'Midfielder' },
	{ name: 'sávio', club: 'Manchester City', nationality: 'Brazil', position: 'Forward' },
	{ name: 'séamus coleman', club: 'Everton', nationality: 'Ireland', position: 'Defender' },
	{ name: 'sean longstaff', club: 'Leeds United', nationality: 'England', position: 'Midfielder' },
	{ name: 'sean neave', club: 'Newcastle', nationality: 'England', position: 'Forward' },
	{ name: 'sebastiaan bornauw', club: 'Leeds United', nationality: 'Belgium', position: 'Defender' },
	{ name: 'senne lammens', club: 'Manchester United', nationality: 'Belgium', position: 'Goalkeeper' },
	{ name: 'sepp van den berg', club: 'Brentford', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'seth ridgeon', club: 'Fulham', nationality: 'England', position: 'Midfielder' },
	{ name: 'seung-soo park', club: 'Newcastle', nationality: 'South Korea', position: 'Forward' },
	{ name: 'shea lacey', club: 'Manchester United', nationality: 'England', position: 'Forward' },
	{ name: 'shumaira mheuka', club: 'Chelsea', nationality: 'England', position: 'Forward' },
	{ name: 'simon moore', club: 'Sunderland', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'solly march', club: 'Brighton & Hove Albion', nationality: 'England', position: 'Right Winger' },
	{ name: 'soungoutou magassa', club: 'West Ham', nationality: 'France', position: 'Midfielder' },
	{ name: 'souza', club: 'Tottenham', nationality: 'Brazil', position: 'Defender' },
	{ name: 'stefan bajcetic', club: 'Liverpool', nationality: 'Spain', position: 'Defender' },
	{ name: 'stefan ortega moreno', club: 'Nottingham Forest', nationality: 'Germany', position: 'Goalkeeper' },
	{ name: 'stefanos tzimas', club: 'Brighton & Hove Albion', nationality: 'Greece', position: 'Forward' },
	{ name: 'sven botman', club: 'Newcastle', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'sverre nypan', club: 'Manchester City', nationality: 'Norway', position: 'Midfielder' },
	{ name: 'taiwo awoniyi', club: 'Nottingham Forest', nationality: 'Nigeria', position: 'Forward' },
	{ name: 'tammy abraham', club: 'Aston Villa', nationality: 'England', position: 'Forward' },
	{ name: 'teddy sharman-lowe', club: 'Chelsea', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'thierno barry', club: 'Everton', nationality: 'France', position: 'Forward' },
	{ name: 'thomas king', club: 'Everton', nationality: 'Wales', position: 'Goalkeeper' },
	{ name: 'thomas mcgill', club: 'Brighton & Hove Albion', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'tijjani reijnders', club: 'Manchester City', nationality: 'Netherlands', position: 'Midfielder' },
	{ name: 'tim iroegbunam', club: 'Everton', nationality: 'England', position: 'Midfielder' },
	{ name: 'timothy castagne', club: 'Fulham', nationality: 'Belgium', position: 'Defender' },
	{ name: 'tj carroll', club: 'Aston Villa', nationality: 'England', position: 'Defender' },
	{ name: 'toluwalas arokodare', club: 'Wolverhampton', nationality: 'Nigeria', position: 'Forward' },
	{ name: 'tom cairney', club: 'Fulham', nationality: 'England', position: 'Midfielder' },
	{ name: 'tom edozie', club: 'Wolverhampton', nationality: 'England', position: 'Midfielder' },
	{ name: 'tom heaton', club: 'Manchester United', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'tomáš souček', club: 'West Ham', nationality: 'Czech Republic', position: 'Midfielder' },
	{ name: 'tommy pilling', club: 'Liverpool', nationality: 'England', position: 'Midfielder' },
	{ name: 'tommy setford', club: 'Arsenal', nationality: 'England', position: 'Goalkeeper' },
	{ name: 'tosin adarabioyo', club: 'Chelsea', nationality: 'England', position: 'Defender' },
	{ name: 'toti gomes', club: 'Wolverhampton', nationality: 'Portugal', position: 'Defender' },
	{ name: 'trai hume', club: 'Sunderland', nationality: 'Northern Ireland', position: 'Defender' },
	{ name: 'trevoh chalobah', club: 'Chelsea', nationality: 'England', position: 'Defender' },
	{ name: 'trey nyoni', club: 'Liverpool', nationality: 'England', position: 'Midfielder' },
	{ name: 'tye hall', club: 'Tottenham', nationality: 'England', position: 'Midfielder' },
	{ name: 'tyler adams', club: 'Bournemouth', nationality: 'USA', position: 'Midfielder' },
	{ name: 'tyler dibling', club: 'Everton', nationality: 'England', position: 'Forward' },
	{ name: 'tyler fletcher', club: 'Manchester United', nationality: 'England', position: 'Midfielder' },
	{ name: 'tyler fredricson', club: 'Manchester United', nationality: 'England', position: 'Defender' },
	{ name: 'tynan thompson', club: 'Tottenham', nationality: 'England', position: 'Forward' },
	{ name: 'tyrell malacia', club: 'Manchester United', nationality: 'Netherlands', position: 'Left-Back' },
	{ name: 'tyrick mitchell', club: 'Crystal Palace', nationality: 'England', position: 'Defender' },
	{ name: 'tyrique george', club: 'Everton', nationality: 'England', position: 'Forward' },
	{ name: 'tyrone mings', club: 'Aston Villa', nationality: 'England', position: 'Defender' },
	{ name: 'tyrone samba', club: 'Manchester City', nationality: 'France', position: 'Midfielder' },
	{ name: 'václav hladký', club: 'Burnley', nationality: 'Czech Republic', position: 'Goalkeeper' },
	{ name: 'valentín castellanos', club: 'West Ham', nationality: 'Argentina', position: 'Forward' },
	{ name: 'valentino livramento', club: 'Newcastle', nationality: 'England', position: 'Defender' },
	{ name: 'veljko milosavljević', club: 'Bournemouth', nationality: 'Serbia', position: 'Defender' },
	{ name: 'victor nilsson-lindelöf', club: 'Aston Villa', nationality: 'Sweden', position: 'Defender' },
	{ name: 'viktor gyökeres', club: 'Arsenal', nationality: 'Sweden', position: 'Forward' },
	{ name: 'virgil van dijk', club: 'Liverpool', nationality: 'Netherlands', position: 'Defender' },
	{ name: 'vitalii mykolenko', club: 'Everton', nationality: 'Ukraine', position: 'Defender' },
	{ name: 'vitaly janelt', club: 'Brentford', nationality: 'Germany', position: 'Midfielder' },
	{ name: 'walter benítez', club: 'Crystal Palace', nationality: 'Argentina', position: 'Goalkeeper' },
	{ name: 'wataru endō', club: 'Liverpool', nationality: 'Japan', position: 'Midfielder' },
	{ name: 'wellity lucky', club: 'Liverpool', nationality: 'England', position: 'Defender' },
	{ name: 'wesley fofana', club: 'Chelsea', nationality: 'France', position: 'Defender' },
	{ name: 'wilfried gnonto', club: 'Leeds United', nationality: 'Italy', position: 'Forward' },
	{ name: 'will hughes', club: 'Crystal Palace', nationality: 'England', position: 'Midfielder' },
	{ name: 'will wright', club: 'Liverpool', nationality: 'England', position: 'Defender' },
	{ name: 'william osula', club: 'Newcastle', nationality: 'Denmark', position: 'Forward' },
	{ name: 'william saliba', club: 'Arsenal', nationality: 'France', position: 'Defender' },
	{ name: 'willy boly', club: 'Nottingham Forest', nationality: 'Ivory Coast', position: 'Centre-Back' },
	{ name: 'wilson isidor', club: 'Sunderland', nationality: 'Haiti', position: 'Forward' },
	{ name: 'wilson odobert', club: 'Tottenham', nationality: 'France', position: 'Forward' },
	{ name: 'xavi simons', club: 'Tottenham', nationality: 'Netherlands', position: 'Midfielder' },
	{ name: 'yankubah minteh', club: 'Brighton & Hove Albion', nationality: 'Gambia', position: 'Forward' },
	{ name: 'yasin ayari', club: 'Brighton & Hove Albion', nationality: 'Sweden', position: 'Midfielder' },
	{ name: 'yegor yarmolyuk', club: 'Brentford', nationality: 'Ukraine', position: 'Midfielder' },
	{ name: 'yerson mosquera', club: 'Wolverhampton', nationality: 'Colombia', position: 'Defender' },
	{ name: 'yoane wissa', club: 'Newcastle', nationality: 'Congo DR', position: 'Forward' },
	{ name: 'youri tielemans', club: 'Aston Villa', nationality: 'Belgium', position: 'Midfielder' },
	{ name: 'yves bissouma', club: 'Tottenham', nationality: 'Mali', position: 'Defensive Midfield' },
	{ name: 'zach abbott', club: 'Nottingham Forest', nationality: 'England', position: 'Defender' },
	{ name: 'zach marsh', club: 'Crystal Palace', nationality: 'England', position: 'Forward' },
	{ name: 'zeki amdouni', club: 'Burnley', nationality: 'Switzerland', position: 'Forward' },
	{ name: 'zian flemming', club: 'Burnley', nationality: 'Netherlands', position: 'Forward' },
	{ name: 'zyan blake', club: 'Nottingham Forest', nationality: 'England', position: 'Forward' },
]

// Diacritic-insensitive comparison key — search/validation shouldn't require
// typing accented characters (e.g. "traore" should find "traoré"); the
// accented form is still what's displayed and stored.
function normaliseKey(name: string): string {
	return name
		.trim()
		.toUpperCase()
		.normalize('NFD')
		.replace(/[̀-ͯ]/g, '')
}

const allFootballerSet = new Set(allFootballers.map((f) => normaliseKey(f.name)))
const allFootballerMap = new Map(allFootballers.map((f) => [normaliseKey(f.name), f]))

export function isValidFullFootballer(name: string): boolean {
	return allFootballerSet.has(normaliseKey(name))
}

export function getFullPlayerData(name: string): Footballer | undefined {
	return allFootballerMap.get(normaliseKey(name))
}

function seededShuffle<T>(arr: T[], seed: number): T[] {
	const result = [...arr]
	let s = seed >>> 0
	for (let i = result.length - 1; i > 0; i--) {
		s = (Math.imul(s, 1664525) + 1013904223) >>> 0
		const j = s % (i + 1)
		;[result[i], result[j]] = [result[j]!, result[i]!]
	}
	return result
}

// Fixed seed — never change this or all past Scout Report answers will shift
const SCOUT_SHUFFLE_SEED = 20260102
const shuffledFootballersScout = seededShuffle(allFootballers, SCOUT_SHUFFLE_SEED)
const scoutAnswerCache = new Map<string, string>()

export function getScoutAnswerForDay(dateStr: string): string {
	if (scoutAnswerCache.has(dateStr)) return scoutAnswerCache.get(dateStr)!
	const idx = getPuzzleNumber(dateStr) - 1
	const len = shuffledFootballersScout.length
	const safeIdx = ((idx % len) + len) % len
	const answer = shuffledFootballersScout[safeIdx]?.name || ''
	scoutAnswerCache.set(dateStr, answer)
	return answer
}

// Player-name suggestions for an autocomplete input, filtered by a
// diacritic-insensitive substring match, excluding already-guessed names.
export function searchFullFootballers(query: string, excludeNames: string[], limit = 8): Footballer[] {
	const q = normaliseKey(query)
	if (!q) return []
	const excluded = new Set(excludeNames.map(normaliseKey))
	return allFootballers.filter((f) => normaliseKey(f.name).includes(q) && !excluded.has(normaliseKey(f.name))).slice(0, limit)
}
