export type Position =
	| 'Goalkeeper'
	| 'Defender'
	| 'Midfielder'
	| 'Forward'
	| 'Centre-Back'
	| 'Defensive Midfield'
	| 'Right Winger'
	| 'Left Winger'
	| 'Left Midfield'
	| 'Attacking Midfield'
	| 'Left-Back'
	| 'Right-Back'
	| 'Central Midfield'
	| 'Centre-Forward'

export interface Footballer {
	name: string
	club: string
	nationality: string
	position: Position
}

// Player data and answer schedule are generated by `yarn update-players`
// (scripts/update-players.ts) — don't edit the JSON by hand.
import players from '../data/players.json'
import schedule from '../data/schedule.json'
import { getUKDateString } from '../utils/dateStreak'

const EPOCH = '01/01/2026' // DD/MM/YYYY — Puzzle #1 launch date

/** A player as stored in app/data/players.json */
export interface RosterPlayer extends Footballer {
	/** Surname as typed in the letter grids (lowercase, no accents) */
	lastName: string
	known: boolean
	dailyKnown: boolean
	pop: number
}
/** [name, club, nationality, position], frozen as the player was on the day */
export type Snapshot = [string, string, string, string]

export const roster = players as RosterPlayer[]
export const answerSchedule = schedule as {
	epoch: string
	daily: { start: number; answers: Snapshot[] }
	scout: { start: number; answers: Snapshot[] }
	spot: { start: number; days: { target: Snapshot; options: string[] }[][] }
}

export const fromSnapshot = ([name, club, nationality, position]: Snapshot): Footballer => ({
	name,
	club,
	nationality,
	position: position as Position,
})

// Answers from yesterday on stay usable even if the player has since left the league
// (today's game must always be guessable); older ones only matter to solution pages,
// which read the frozen snapshot directly
export const recentFrom = getPuzzleNumber(getUKDateString()) - 1

// Daily: every current player whose surname is six letters is a valid guess, plus
// recent answers. Most famous first, so a shared surname maps to the better-known player.
const dailyHistory = answerSchedule.daily.answers
	.slice(Math.max(0, recentFrom - answerSchedule.daily.start))
	.map(fromSnapshot)
export const footballers: Footballer[] = (() => {
	const seen = new Set<string>()
	const list: Footballer[] = []
	const add = (f: Footballer) => {
		const k = f.name.toUpperCase()
		if (!seen.has(k)) {
			seen.add(k)
			list.push(f)
		}
	}
	for (const p of roster) {
		if (p.lastName.length === 6) add({ name: p.lastName, club: p.club, nationality: p.nationality, position: p.position })
	}
	for (const f of [...dailyHistory].reverse()) add(f)
	return list
})()


// Fast O(1) lookups
const footballerSet = new Set(footballers.map((f) => f.name.toUpperCase()))
const footballerMap = new Map(footballers.map((f) => [f.name.toUpperCase(), f]))

// Cache for memoized daily answers
const answerCache = new Map<string, string>()


// Seed for the fallback pick only; scheduled answers never depend on it
const SHUFFLE_SEED = 20260101

function seededShuffle<T>(arr: T[], seed: number): T[] {
	const result = [...arr]
	let s = seed >>> 0
	for (let i = result.length - 1; i > 0; i--) {
		s = (Math.imul(s, 1664525) + 1013904223) >>> 0
		const j = s % (i + 1)
		;[result[i], result[j]] = [result[j]!, result[i]!]
	}
	return result
}

// Only used past the end of the schedule (an app build that hasn't been updated in
// months): a deterministic pick from today's Daily-eligible players
const dailyFallbackPool = seededShuffle(
	roster.filter(p => p.dailyKnown && p.lastName.length === 6).map(p => p.lastName),
	SHUFFLE_SEED,
)

// Broad position groups used for Scout Report's partial-credit matching —
// a wrong-but-same-group guess (e.g. Right-Back vs Centre-Back) reads as
// "present" rather than "absent".
export type PositionGroup = 'Goalkeeper' | 'Defender' | 'Midfielder' | 'Forward'

const POSITION_GROUPS: Record<Position, PositionGroup> = {
	Goalkeeper: 'Goalkeeper',
	Defender: 'Defender',
	'Centre-Back': 'Defender',
	'Left-Back': 'Defender',
	'Right-Back': 'Defender',
	Midfielder: 'Midfielder',
	'Defensive Midfield': 'Midfielder',
	'Central Midfield': 'Midfielder',
	'Attacking Midfield': 'Midfielder',
	'Left Midfield': 'Midfielder',
	Forward: 'Forward',
	'Centre-Forward': 'Forward',
	'Right Winger': 'Forward',
	'Left Winger': 'Forward',
}

export function getPositionGroup(position: Position): PositionGroup {
	return POSITION_GROUPS[position]
}

export function getPuzzleNumber(dateStr: string): number {
	const [d1, m1, y1] = EPOCH.split('/').map(Number)
	const [d2, m2, y2] = dateStr.split('/').map(Number)
	const epochDate = new Date(y1!, m1! - 1, d1)
	const todayDate = new Date(y2!, m2! - 1, d2)
	const diff = Math.round((todayDate.getTime() - epochDate.getTime()) / (24 * 60 * 60 * 1000))
	return diff + 1
}

// A scheduled Daily answer must fit the six-letter board; anything else (a bad data
// update) is ignored in favour of the fallback rather than making the day unwinnable
function dailyEntry(puzzle: number) {
	const entry = answerSchedule.daily.answers[puzzle - answerSchedule.daily.start]
	return entry && /^[a-z]{6}$/i.test(entry[0]) ? entry : undefined
}

export function getAnswerForDay(dateStr: string): string {
	if (answerCache.has(dateStr)) return answerCache.get(dateStr)!
	const puzzle = getPuzzleNumber(dateStr)
	const scheduled = dailyEntry(puzzle)
	const len = dailyFallbackPool.length
	const answer = scheduled?.[0] ?? dailyFallbackPool[(((puzzle - 1) % len) + len) % len] ?? ''
	answerCache.set(dateStr, answer)
	return answer
}

/** The full name behind a Daily surname, from the roster (same surname and club) */
export function fullNameFor(player: Footballer): string | undefined {
	const key = player.name.toLowerCase()
	return roster.find(p => p.lastName === key && p.club === player.club)?.name
}

/** The answer for a date with its clues as they were that day (club, nation, position) */
export function getAnswerPlayerForDay(dateStr: string): Footballer | undefined {
	const scheduled = dailyEntry(getPuzzleNumber(dateStr))
	return scheduled ? fromSnapshot(scheduled) : getPlayerData(getAnswerForDay(dateStr))
}

export function isValidFootballer(name: string): boolean {
	return footballerSet.has(name.toUpperCase())
}

export function getPlayerData(name: string): Footballer | undefined {
	return footballerMap.get(name.toUpperCase())
}
